services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: auth_project
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: auth_project
      DB_USER: root
      DB_PASSWORD: ""
      DB_HOST: host.docker.internal
